include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: ["lib/**.g.dart"]

linter:
  rules:
    # always_use_package_imports: false

    avoid_dynamic_calls: true
    avoid_print: false
    # avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    use_build_context_synchronously: true # maybe ?
    use_key_in_widget_constructors: false # maybe
    # styling
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    # always_specify_types: false # maybe
    avoid_bool_literals_in_conditional_expressions: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    # avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: false
    avoid_multiple_declarations_per_line: true
    # avoid_positional_boolean_parameters: true
    # avoid_private_typedef_functions: true
    avoid_renaming_method_parameters: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    curly_braces_in_flow_control_structures: true
    leading_newlines_in_multiline_strings: true
    no_runtimeType_toString: true
    omit_local_variable_types: true
    noop_primitive_operations: true
    null_check_on_nullable_type_parameter: true # maybe
    only_throw_errors: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_function_declarations_over_variables: false
    prefer_if_elements_to_conditional_expressions: true
    prefer_null_aware_method_calls: true
    prefer_single_quotes: false
    require_trailing_commas: true
    sort_child_properties_last: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: false
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_null_aware_assignments: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_parenthesis: true
    unnecessary_this: false
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
